# Site settings
title: BeaugTech
email: info@beaugtech.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.beaugtech.com" # the base hostname & protocol for your site

# Contact list
twitter_username:
github_username: Matt95B
linkedin_username: Matt95B
youtube_username: BeaugTech

# Build settings
markdown: kramdown
